# Development override for docker-compose.yml
# This file is automatically loaded when running docker-compose

version: '3.8'

services:
  openacidminedrainage:
    environment:
      - LOG_LEVEL=DEBUG
      - PYTHONPATH=/app/src
    volumes:
      - .:/app
      - /app/__pycache__
    command: ["uvicorn", "open_sedimentation_manager.api:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]

  # Enable development API service by default
  api-dev:
    profiles: []  # Remove profile requirement for development
